Controllers/ViagensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using X.PagedList;
using TechPort.Data;
using TechPort.Models;

namespace TechPort.Controllers
{
    public class ViagensController : Controller
    {
        private readonly ApplicationDbContext _context;
        private int? page;

        public ViagensController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize]
        // GET: Viagens
        public async Task<IActionResult> Index(int? page, String searchString)
        {
            var pageNumber = page ?? 1;
            var pageSize = 3;

            var viagens = _context.Viagens.Include(v => v.Navio).AsQueryable();

            if (!String.IsNullOrEmpty(searchString))
            {
                var filteredViagens = viagens.Where(v => v.Codigo.Contains(searchString));
                viagens = filteredViagens;
            }

            var pagedViagens = await viagens.ToPagedListAsync(pageNumber, pageSize);

            ViewBag.SearchString = searchString; // Adiciona a string de pesquisa à ViewBag para que ela possa ser exibida na View

            return View(pagedViagens);
        }

        [Authorize]
        // GET: Viagens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Viagens == null)
            {
                return NotFound();
            }

            var viagem = await _context.Viagens
                .Include(v => v.Navio)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (viagem == null)
            {
                return NotFound();
            }

            return View(viagem);
        }

        [Authorize]
        // GET: Viagens/Create
        public IActionResult Create()
        {
            ViewData["NavioId"] = new SelectList(_context.Navios, "Id", "Nome");
            return View();
        }

        [Authorize]
        // POST: Viagens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Codigo,NavioId,TipoViagem")] Viagem viagem)
        {
            ModelState.Clear();
            if (ModelState.IsValid)
            {
                _context.Add(viagem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["NavioId"] = new SelectList(_context.Navios, "Id", "Nome", viagem.NavioId);
            return View(viagem);
        }

        [Authorize]
        // GET: Viagens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Viagens == null)
            {
                return NotFound();
            }

            var viagem = await _context.Viagens.FindAsync(id);
            if (viagem == null)
            {
                return NotFound();
            }
            ViewData["NavioId"] = new SelectList(_context.Navios, "Id", "Nome", viagem.NavioId);
            return View(viagem);
        }

        [Authorize]
        // POST: Viagens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Codigo,NavioId,TipoViagem")] Viagem viagem)
        {
            if (id != viagem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(viagem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ViagemExists(viagem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["NavioId"] = new SelectList(_context.Navios, "Id", "Nome", viagem.NavioId);
            return View(viagem);
        }

        [Authorize]
        // GET: Viagens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Viagens == null)
            {
                return NotFound();
            }

            var viagem = await _context.Viagens
                .Include(v => v.Navio)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (viagem == null)
            {
                return NotFound();
            }

            return View(viagem);
        }

        [Authorize]
        // POST: Viagens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Viagens == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Viagens'  is null.");
            }
            var viagem = await _context.Viagens.FindAsync(id);
            if (viagem != null)
            {
                _context.Viagens.Remove(viagem);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ViagemExists(int id)
        {
          return _context.Viagens.Any(e => e.Id == id);
        }
    }
}

Views/Viagens/Create.cshtml
@model TechPort.Models.Viagem

@{
    ViewData["Title"] = "Create";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.8/jquery.mask.js"></script>

<h1>Criar</h1>

<h4>Viagem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input id="viagem" asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NavioId" class="control-label"></label>
                <select asp-for="NavioId" class="form-control" asp-items="ViewBag.NavioId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TipoViagem" class="control-label"></label>
                <select asp-for="TipoViagem" class="form-control" asp-items="Html.GetEnumSelectList<TechPort.Models.Enums.TipoViagem>()"></select>
                <span asp-validation-for="TipoViagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à Lista</a>
</div>

<script>
    jQuery(function ($) {
         $('#viagem').mask('SS999999', {
            'translation': {
                S: {pattern: /[A-Za-z]/},
                0: {pattern: /[0-9]/}
            }
            ,onKeyPress: function (value, event) {
                event.currentTarget.value = value.toUpperCase();
            }
    });
</script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Viagens/Delete.cshtml
@model TechPort.Models.Viagem

@{
    ViewData["Title"] = "Delete";
}

<h1>Excluir</h1>

<div>
    <h4>Viagem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Navio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Navio.Empresa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoViagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoViagem)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar à Lista</a>
    </form>
</div>

Views/Viagens/Details.cshtml
@model TechPort.Models.Viagem

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Viagem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Navio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Navio.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoViagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoViagem)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Editar</a> |
    <a asp-action="Index">Voltar à Lista</a>
</div>

Views/Viagens/Edit.cshtml
@model TechPort.Models.Viagem

@{
    ViewData["Title"] = "Edit";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.8/jquery.mask.js"></script>


<h1>Editar</h1>

<h4>Viagem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input id="nome" asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NavioId" class="control-label"></label>
                <select asp-for="NavioId" class="form-control" asp-items="ViewBag.NavioId"></select>
                <span asp-validation-for="NavioId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoViagem" class="control-label"></label>
                <select asp-for="TipoViagem" class="form-control" asp-items="Html.GetEnumSelectList<TechPort.Models.Enums.TipoViagem>()"></select>
                <span asp-validation-for="TipoViagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à Lista</a>
</div>

<script>
    jQuery(function ($) {
        $('#viagem').mask('SS999999', {
            'translation': {
                S: { pattern: /[A-Za-z]/ },
                0: { pattern: /[0-9]/ }
            }
            , onKeyPress: function (value, event) {
                event.currentTarget.value = value.toUpperCase();
            }
        });
</script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Viagens/Index.cshtml
@model X.PagedList.IPagedList<TechPort.Models.Viagem>
@using X.PagedList.Mvc.Core;
@using X.PagedList;


@{
    ViewData["Title"] = "Index";
}

<h1>Viagens</h1>

<form asp-controller="Viagens" asp-action="Index">
    <p>
        Codigo: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<p>
    @Html.ActionLink("Cadastrar Nova Viagem", "Create", new {id = "" }, new {@class = "btn btn-primary"})
</p>
<table class="table table-secondary table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model[0].Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Navio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].TipoViagem)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Navio.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoViagem)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new {id = item.Id}, new {@class = "btn btn-outline-primary"})
                    @Html.ActionLink("Detalhes", "Details", new {id = item.Id }, new {@class = "btn btn-outline-primary"})
                    @Html.ActionLink("Excluir", "Delete", new {id = item.Id}, new {@class = "btn btn-outline-danger"})
                </td>
            </tr>
        }
    </tbody>

</table>

<div class="text-center">
    @(Html.PagedListPager(Model, page => Url.Action("Index", new { page })))
</div>