Models/Conteiner.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace TechPort.Models
{
    public class Conteiner
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(11)]
        [MinLength(11)]
        [Display(Name ="Container")]
        public string Nome { get; set; }
        [Required]
        public string Tipo { get; set; }
        [Display(Name = "Empresa")]
        public int? EmpresaId { get; set; }

        public Empresa? Empresa { get; set; }

        public IList<VidaConteiner>? VidaConteinerList { get;set; }
    }
}

Controllers/ConteinersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using X.PagedList;
using TechPort.Data;
using TechPort.Models;
using System.ComponentModel;

namespace TechPort.Controllers
{
    public class ConteinersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ConteinersController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize]
        // GET: Conteiners
        public async Task<IActionResult> Index(int? page, String searchString)
        {
            var pageNumber = page ?? 1; // se o parâmetro page for nulo, use a primeira página como padrão
            var pageSize = 3; // defina o número de registros exibidos em cada página

            var conteiners = _context.Conteiners.Include(v => v.Empresa).AsQueryable();

            if (!String.IsNullOrEmpty(searchString))
            {
                var filteredConteiners = conteiners.Where(v => v.Nome.Contains(searchString));
                conteiners = filteredConteiners;
            }
            var pagedConteiners = await conteiners.ToPagedListAsync(pageNumber, pageSize);

            ViewBag.SearchString = searchString; // Adiciona a string de pesquisa à ViewBag para que ela possa ser exibida na View

            return View(pagedConteiners);

        }

        [Authorize]
        // GET: Conteiners/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Conteiners == null)
            {
                return NotFound();
            }

            var conteiner = await _context.Conteiners
                .Include(c => c.Empresa)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (conteiner == null)
            {
                return NotFound();
            }

            return View(conteiner);
        }

        [Authorize]
        // GET: Conteiners/Create
        public IActionResult Create()
        {
            ViewData["EmpresaId"] = new SelectList(_context.Empresa, "Id", "Nome");
            return View();
        }

        // POST: Conteiners/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Tipo,EmpresaId")] Conteiner conteiner)
        {
            ModelState.Clear();
            if (ModelState.IsValid)
            {
                _context.Add(conteiner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpresaId"] = new SelectList(_context.Empresa, "Id", "Nome", conteiner.EmpresaId);
            return View(conteiner);
        }

        [Authorize]
        // GET: Conteiners/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Conteiners == null)
            {
                return NotFound();
            }

            var conteiner = await _context.Conteiners.FindAsync(id);
            if (conteiner == null)
            {
                return NotFound();
            }
            ViewData["EmpresaId"] = new SelectList(_context.Empresa, "Id", "Nome", conteiner.EmpresaId);
            return View(conteiner);
        }

        // POST: Conteiners/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Tipo,EmpresaId")] Conteiner conteiner)
        {
            if (id != conteiner.Id)
            {
                return NotFound();
            }

            ModelState.Clear();
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(conteiner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConteinerExists(conteiner.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpresaId"] = new SelectList(_context.Empresa, "Id", "Nome", conteiner.EmpresaId);
            return View(conteiner);
        }

        [Authorize]
        // GET: Conteiners/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Conteiners == null)
            {
                return NotFound();
            }

            var conteiner = await _context.Conteiners
                .Include(c => c.Empresa)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (conteiner == null)
            {
                return NotFound();
            }

            return View(conteiner);
        }

        [Authorize]
        // POST: Conteiners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Conteiners == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Conteiners'  is null.");
            }
            var conteiner = await _context.Conteiners.FindAsync(id);
            if (conteiner != null)
            {
                _context.Conteiners.Remove(conteiner);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ConteinerExists(int id)
        {
          return _context.Conteiners.Any(e => e.Id == id);
        }
    }
}

Views/Conteiners/Create.cshtml
@model TechPort.Models.Conteiner

@{
    ViewData["Title"] = "Create";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.8/jquery.mask.js"></script>

<h1>Criar</h1>

<h4>Container</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input id="nome" asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpresaId" class="control-label"></label>
                <select asp-for="EmpresaId" class ="form-control" asp-items="ViewBag.EmpresaId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à Lista</a>
</div>

<script>
    jQuery(function ($) {
        $('#nome').mask('SSSS9999999', {
            'translation': {
                S: {pattern: /[A-Za-z]/},
                0: {pattern: /[0-9]/}
            }
            ,onKeyPress: function (value, event) {
                event.currentTarget.value = value.toUpperCase();
            }
})
    });
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Conteiners/Delete.cshtml
@model TechPort.Models.Conteiner

@{
    ViewData["Title"] = "Delete";
}

<h1>Excluir</h1>

<div>
    <h4>Container</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.Nome)*@ @Html.LabelFor(model => model.Nome, "Container", htmlAttributes: new { @class = "control-label col-md-2" })
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empresa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empresa.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar à Lista</a>
    </form>
</div>

Views/Conteiners/Details.cshtml
@model TechPort.Models.Conteiner

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Container</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.Nome)*@ @Html.LabelFor(model => model.Nome, "Container", htmlAttributes: new { @class = "control-label col-md-2" })
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empresa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empresa.Nome)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Editar</a> |
    <a asp-action="Index">Voltar à Lista</a>
</div>

Views/Conteiners/Edit.cshtml
@model TechPort.Models.Conteiner

@{
    ViewData["Title"] = "Edit";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.8/jquery.mask.js"></script>


<h1>Editar</h1>

<h4>Container</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input id="nome" asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpresaId" class="control-label"></label>
                <select asp-for="EmpresaId" class="form-control" asp-items="ViewBag.EmpresaId"></select>
                <span asp-validation-for="EmpresaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à Lista</a>
</div>

<script>
    jQuery(function ($) {
        $('#nome').mask('SSSS9999999', {
            'translation': {
                S: { pattern: /[A-Za-z]/ },
                0: { pattern: /[0-9]/ }
            }
            , onKeyPress: function (value, event) {
                event.currentTarget.value = value.toUpperCase();
            }
        })
    });
</script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Conteiners/Index.cshtml
@model X.PagedList.IPagedList<TechPort.Models.Conteiner>
@using X.PagedList.Mvc.Core;
@using X.PagedList;

@{
    ViewData["Title"] = "Index";
}

<h1>Containers</h1>

<form action="@Url.Action("Index", "Conteiners")" method="get">
    <p>
        Nome: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<p>
    @Html.ActionLink("Cadastrar Novo Container", "Create", new {id = "" }, new {@class = "btn btn-primary"})
</p>
<table class="table table-secondary table-striped">
    <thead>
        <tr>
            <th>
                @* @Html.DisplayNameFor(model => model.Nome)*@ @Html.LabelFor(model => model.FirstOrDefault().Nome, "Container", htmlAttributes: new { @class = "control-label col-md-2" })
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Tipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Empresa)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Empresa.Nome)
            </td>
            <td>
                    @Html.ActionLink("Editar", "Edit", new {id = item.Id}, new {@class = "btn btn-outline-primary"})
                    @Html.ActionLink("Detalhes", "Details", new {id = item.Id }, new {@class = "btn btn-outline-primary"})
                    @Html.ActionLink("Excluir", "Delete", new {id = item.Id}, new {@class = "btn btn-outline-danger"})
            </td>
        </tr>
}
    </tbody>
</table>

<div class="text-center">
    @(Html.PagedListPager(Model, page => Url.Action("Index", new { page })))
</div>