Controllers/VidasConteinersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using X.PagedList;
using TechPort.Data;
using TechPort.Models;

namespace TechPort.Controllers
{
    public class VidasConteinersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VidasConteinersController(ApplicationDbContext context)
        {
            _context = context;

        }

        [Authorize]
        // GET: VidasConteiners
        public async Task<IActionResult> Index(int? page,String searchString, String searchString2, String searchString3)
        {

            var pageNumber = page ?? 1; // se o parâmetro page for nulo, use a primeira página como padrão
            var pageSize = 3; // defina o número de registros exibidos em cada página

            var vidaConteiners = _context.VidasConteiner.Include(v => v.Conteiner).Include(v => v.Viagem).AsQueryable();

            System.Linq.IQueryable<TechPort.Models.VidaConteiner> filteredVidas;

            if (!String.IsNullOrEmpty(searchString) && !String.IsNullOrEmpty(searchString2) && !String.IsNullOrEmpty(searchString3))
            {
                 filteredVidas = vidaConteiners.Where(v => v.Conteiner.Nome.Contains(searchString) && v.Navio.Contains(searchString3) && v.Viagem.Codigo.Contains(searchString2));
                vidaConteiners = filteredVidas;
            }
            else if (String.IsNullOrEmpty(searchString) && !String.IsNullOrEmpty(searchString2) && !String.IsNullOrEmpty(searchString3))
            {
                 filteredVidas = vidaConteiners.Where(v => v.Navio.Contains(searchString3) && v.Viagem.Codigo.Contains(searchString2));
                vidaConteiners = filteredVidas;
            }
            else if (!String.IsNullOrEmpty(searchString) && String.IsNullOrEmpty(searchString2) && !String.IsNullOrEmpty(searchString3))
            {
                 filteredVidas = vidaConteiners.Where(v => v.Conteiner.Nome.Contains(searchString) && v.Navio.Contains(searchString3));
                vidaConteiners = filteredVidas;
            }
            else if (!String.IsNullOrEmpty(searchString) && !String.IsNullOrEmpty(searchString2) && String.IsNullOrEmpty(searchString3))
            {
                 filteredVidas = vidaConteiners.Where(v => v.Conteiner.Nome.Contains(searchString) && v.Viagem.Codigo.Contains(searchString2));
                vidaConteiners = filteredVidas;
            }
            else if (!String.IsNullOrEmpty(searchString) && String.IsNullOrEmpty(searchString2) && String.IsNullOrEmpty(searchString3))
            {
                 filteredVidas = vidaConteiners.Where(v => v.Conteiner.Nome.Contains(searchString));
                vidaConteiners = filteredVidas;

            }
            else if (String.IsNullOrEmpty(searchString) && !String.IsNullOrEmpty(searchString2) && String.IsNullOrEmpty(searchString3))
            {
                 filteredVidas = vidaConteiners.Where(v => v.Viagem.Codigo.Contains(searchString2));
                vidaConteiners = filteredVidas;

            }
            else if (String.IsNullOrEmpty(searchString) && String.IsNullOrEmpty(searchString2) && !String.IsNullOrEmpty(searchString3))
            {
                 filteredVidas = vidaConteiners.Where(v => v.Navio.Contains(searchString3));
                vidaConteiners = filteredVidas;

            }

            

            var pagedVidas = await vidaConteiners.ToPagedListAsync(pageNumber, pageSize);

            ViewBag.SearchString = searchString; // Adiciona a string de pesquisa à ViewBag para que ela possa ser exibida na View

            return View(pagedVidas);
        }

        [Authorize]
        // GET: VidasConteiners/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.VidasConteiner == null)
            {
                return NotFound();
            }

            var vidaConteiner = await _context.VidasConteiner
                .Include(v => v.Conteiner)
                .Include(v => v.Viagem)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vidaConteiner == null)
            {
                return NotFound();
            }

            return View(vidaConteiner);
        }

        [Authorize]
        // GET: VidasConteiners/Create
        public IActionResult Create()
        {
            ViewData["ConteinerId"] = new SelectList(_context.Conteiners, "Id", "Nome");
            ViewData["ViagemId"] = new SelectList(_context.Viagens, "Id", "Codigo");
            return View();
        }

        [Authorize]
        // POST: VidasConteiners/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ConteinerId,StatusConteiner,ViagemId,Navio,Etapa")] VidaConteiner vidaConteiner)
        {
            #region Inclui Nome do Navio Diretamente na Coluna
            var NavioContext = _context.Viagens.Include(v => v.Navio);
            vidaConteiner.Navio = NavioContext.Where(v => v.Id == vidaConteiner.ViagemId).Select(v => v.Navio.Nome).FirstOrDefault();        
            #endregion


            ModelState.Clear();

            if (ModelState.IsValid)
            {
                _context.Add(vidaConteiner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ConteinerId"] = new SelectList(_context.Conteiners, "Id", "Nome", vidaConteiner.ConteinerId);
            ViewData["ViagemId"] = new SelectList(_context.Viagens, "Id", "Codigo", vidaConteiner.ViagemId);
            ViewData["NavioId"] = new SelectList(_context.Navios, "Id", "Nome", vidaConteiner.Viagem.NavioId);
            return View(vidaConteiner);
        }

        [Authorize]
        // GET: VidasConteiners/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.VidasConteiner == null)
            {
                return NotFound();
            }

            var vidaConteiner = await _context.VidasConteiner.FindAsync(id);
            if (vidaConteiner == null)
            {
                return NotFound();
            }
            ViewData["ConteinerId"] = new SelectList(_context.Conteiners, "Id", "Nome", vidaConteiner.ConteinerId);
            ViewData["ViagemId"] = new SelectList(_context.Viagens, "Id", "Codigo", vidaConteiner.ViagemId);
            return View(vidaConteiner);
        }

        [Authorize]
        // POST: VidasConteiners/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ConteinerId,StatusConteiner,ViagemId,Navio,Etapa")] VidaConteiner vidaConteiner)
        {
            if (id != vidaConteiner.Id)
            {
                return NotFound();
            }

            #region Inclui Nome do Navio Diretamente na Coluna
            var NavioContext = _context.Viagens.Include(v => v.Navio);
            vidaConteiner.Navio = NavioContext.Where(v => v.Id == vidaConteiner.ViagemId).Select(v => v.Navio.Nome).FirstOrDefault();
            #endregion

            ModelState.Clear();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vidaConteiner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VidaConteinerExists(vidaConteiner.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ConteinerId"] = new SelectList(_context.Conteiners, "Id", "Nome", vidaConteiner.ConteinerId);
            ViewData["ViagemId"] = new SelectList(_context.Viagens, "Id", "Codigo", vidaConteiner.ViagemId);
            return View(vidaConteiner);
        }

        [Authorize]
        // GET: VidasConteiners/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.VidasConteiner == null)
            {
                return NotFound();
            }

            var vidaConteiner = await _context.VidasConteiner
                .Include(v => v.Conteiner)
                .Include(v => v.Viagem)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vidaConteiner == null)
            {
                return NotFound();
            }

            return View(vidaConteiner);
        }

        [Authorize]
        // POST: VidasConteiners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.VidasConteiner == null)
            {
                return Problem("Entity set 'ApplicationDbContext.VidasConteiner'  is null.");
            }
            var vidaConteiner = await _context.VidasConteiner.FindAsync(id);
            if (vidaConteiner != null)
            {
                _context.VidasConteiner.Remove(vidaConteiner);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

Views/VidasConteiners/Create.cshtml
@model TechPort.Models.VidaConteiner

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>

<h4>Operações de Containers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ConteinerId" class="control-label"></label>
                <select asp-for="ConteinerId" class ="form-control" asp-items="ViewBag.ConteinerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="StatusConteiner" class="control-label"></label>
                <select asp-for="StatusConteiner" class="form-control" asp-items="Html.GetEnumSelectList<TechPort.Models.Enums.StatusConteiner>()"></select>
                <span asp-validation-for="StatusConteiner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ViagemId" class="control-label"></label>
                <select asp-for="ViagemId" class ="form-control" asp-items="ViewBag.ViagemId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Etapa" class="control-label"></label>
                <select asp-for="Etapa" class="form-control" asp-items="Html.GetEnumSelectList<TechPort.Models.Enums.Etapa>()"></select>
                <span asp-validation-for="Etapa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/VidasConteiners/Delete.cshtml
@model TechPort.Models.VidaConteiner

@{
    ViewData["Title"] = "Delete";
}

<h1>Excluir</h1>

<div>
    <h4>Operações de Containers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Conteiner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Conteiner.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StatusConteiner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatusConteiner)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Viagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Viagem.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Navio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Navio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Etapa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Etapa)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar à Lista</a>
    </form>
</div>

Views/VidasConteiners/Details.cshtml
@model TechPort.Models.VidaConteiner

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Operações de Containers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @*@Html.DisplayNameFor(model => model.Conteiner)*@ @Html.LabelFor(model => model.Conteiner, "Container", htmlAttributes: new { @class = "control-label col-md-2" })
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Conteiner.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StatusConteiner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatusConteiner)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Viagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Viagem.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Navio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Viagem.NavioId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Etapa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Etapa)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Editar</a> |
    <a asp-action="Index">Voltar à Lista</a>
</div>

Views/VidasConteiners/Edit.cshtml
@model TechPort.Models.VidaConteiner

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Operações de Containers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ConteinerId" class="control-label"></label>
                <select asp-for="ConteinerId" class="form-control" asp-items="ViewBag.ConteinerId"></select>
                <span asp-validation-for="ConteinerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusConteiner" class="control-label"></label>
                <select asp-for="StatusConteiner" class="form-control" asp-items="Html.GetEnumSelectList<TechPort.Models.Enums.StatusConteiner>()"></select>
                <span asp-validation-for="StatusConteiner" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ViagemId" class="control-label"></label>
                <select asp-for="ViagemId" class="form-control" asp-items="ViewBag.ViagemId"></select>
                <span asp-validation-for="ViagemId" class="text-danger"></span>
            </div>
       @*     <div class="form-group">
                <label asp-for="Navio" class="control-label"></label>
                <input asp-for="Navio" class="form-control" />
                <span asp-validation-for="Navio" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Etapa" class="control-label"></label>
                <select asp-for="Etapa" class="form-control" asp-items="Html.GetEnumSelectList<TechPort.Models.Enums.Etapa>()"></select>
                <span asp-validation-for="Etapa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/VidasConteiners/Index.cshtml
@model X.PagedList.IPagedList<TechPort.Models.VidaConteiner>
@using X.PagedList.Mvc.Core;
@using X.PagedList;

@{
    ViewData["Title"] = "Index";
}

<h1>Operações de Containers</h1>

<form action="@Url.Action("Index", "VidasConteiners")" method="get">
    <p>
        Conteiner: <input type="text" name="SearchString" />
        Viagem: <input type="text" name="SearchString2" />
        Navio: <input type="text" name="SearchString3" />
        <input type="submit" value="Filter" />
    </p>
</form>

<p>
    @Html.ActionLink("Criar Nova Operação", "Create", new {id = "" }, new {@class = "btn btn-primary"})
</p>
<table class="table table-secondary table-striped">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.Conteiner)*@ @Html.LabelFor(model => model.FirstOrDefault().Conteiner, "Container", htmlAttributes: new { @class = "control-label col-md-2" })
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].StatusConteiner)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Viagem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Navio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Etapa)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Conteiner.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatusConteiner)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Viagem.Codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Navio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Etapa)
            </td>
            <td>
                    @Html.ActionLink("Editar", "Edit", new {id = item.Id}, new {@class = "btn btn-outline-primary"})   
                    @Html.ActionLink("Detalhes", "Details", new {id = item.Id }, new {@class = "btn btn-outline-primary"})   
                    @Html.ActionLink("Excluir", "Delete", new {id = item.Id}, new {@class = "btn btn-outline-danger"})
            </td>
        </tr>
}
    </tbody>
</table>


<div class="text-center">
    @(Html.PagedListPager(Model, page => Url.Action("Index", new { page })))
</div>